### ISSUE TITLE
Android build instructions/repo manifest?

### ISSUE THREAD

**Issue by du5t** [wireapp/zmessaging-android#1]
hi, i'm writing this here because there doesn't seem to be a repository corresponding to the android app, and i think it would be friendlier to ask this question in a semi-public forum.

on your marketing website, the copy states:

> We made the source code for data handling available to the public under the GPL License. This means that anybody can review the source code.

this is very welcome, but what about the rest? taking the strict view, everything that wraps around the "data handling" code is currently opaque and could therefore be anything, including things that compromise the apparent promises made by the currently available code. on a more pragmatic level, since you seem to be positioned as a more flexible alternative to whispersystems' signal app, making it so that users and providers like f-droid, who aren't inside a walled garden like google play, can also build and run wire would net you a big gain in passionate users. see https://github.com/WhisperSystems/Signal-Android/issues/127 for evidence.

it's true that the gpl doesn't require you to do anything but publish source code, and in a world where open source rules over free software, it's heartening to see so many repos under gpl v3 :) saying that, a manifest of repositories required to build the complete application would be quite a boost, and build instructions for the whole kit would be wonderful.

please let the community know if you plan to make an open source wireapp build possible, and how long you expect it will take to get the code to us so we can try it.

thanks!

**Comment by wireswiss** [comment]
Thank you for your comment @du5t!

Our first priority was to open source the parts related to cryptography as well as the data handling part.
We will soon add more documentation and build instructions. We would also like to open source more parts of the application in the future.

In the meantime we will have a review of all our source code done by an independent third party, to provide the users with more guarantees about the parts that are not yet open sourced.

**Comment by cryptono** [comment]
@wireswiss Is your aim to publish all of the code or just parts of it? Please be more concretely: When will you publish all other parts of the code? Users just can be sure that there are no back doors if you publish the hole code.

**Comment by zbsz** [comment]
All client code is open source now, here is the android client repo (together with build scripts): https://github.com/wireapp/wire-android. Have fun.
